### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by datatalking** [hitensam/Library-Management#6]
@hitensam from the requirements.txt file I am guessing this is a Flask app which isn't my core but since its Python I can probably get it working.

Do you have a 'how to run flask' tutorial or can we update the README.md to include installation instructions?

**Comment by hitensam** [comment]
@datatalking If you want to update README.md, you are welcome! 😃  

To get the code working:
1. Install flask using pip, on CMD/Terminal run (pip install flask)
2. You need to configure the db.py file for firebase to work refer: [pyrebase4](https://github.com/nhorvath/Pyrebase4)
3. The code may not be working as intended. Please review it to see if any changes need to be made.

**Comment by datatalking** [comment]
@hitensam 

```
(Library-Management) user_name:~/PycharmProjects/Library-Management (MacOS) $ python app.py
Traceback (most recent call last):
  File "/Users/user_name/PycharmProjects/Library-Management/app.py", line 5, in <module>
    import db as fb
  File "/Users/user_name/PycharmProjects/Library-Management/db.py", line 1, in <module>
    import pyrebase
  File "/Users/user_name/opt/anaconda3/envs/Library-Management/lib/python3.10/site-packages/pyrebase/__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "/Users/user_name/opt/anaconda3/envs/Library-Management/lib/python3.10/site-packages/pyrebase/pyrebase.py", line 1, in <module>
    import requests
  File "/Users/user_name/opt/anaconda3/envs/Library-Management/lib/python3.10/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/Users/user_name/opt/anaconda3/envs/Library-Management/lib/python3.10/site-packages/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/Users/user_name/opt/anaconda3/envs/Library-Management/lib/python3.10/site-packages/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```
I've installed the requirements.txt, tried python 3.10 and conda with no success. Does this only work on windows machines or ?

**Comment by datatalking** [comment]
@hitensam ok I tried python 3.10, 3.9, and 3.8 with no luck but python 3.7 via anaconda does load, and I'll start with some basic tests. It runs but gives package mismatches below, all of this will be hopefully addressed, patched or fixed in the PR I submit later today. =)

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyrebase 3.0.27 requires gcloud==0.17.0, but you have gcloud 0.18.3 which is incompatible.
pyrebase 3.0.27 requires oauth2client==3.0.0, but you have oauth2client 4.1.3 which is incompatible.
pyrebase 3.0.27 requires pycryptodome==3.4.3, but you have pycryptodome 3.18.0 which is incompatible.
pyrebase 3.0.27 requires requests==2.11.1, but you have requests 2.29.0 which is incompatible.
pyrebase 3.0.27 requires requests-toolbelt==0.7.0, but you have requests-toolbelt 0.10.1 which is incompatible.
```
